name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Create static files
        run: |
          mkdir -p dist
          cp README.md dist/
          cp postman-collection.json dist/
          cp postman-environment.json dist/
          cp example-data.js dist/
          cp package.json dist/
          cp ENTREGA.md dist/
          
      - name: Create index.html
        uses: "DamianReeves/write-file-action@master"
        with:
          path: dist/index.html
          write-mode: overwrite
          contents: |
            <!DOCTYPE html>
            <html lang="pt-BR">
            <head>
                <meta charset="UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <title>API CRUD - OAT1 Pedro Borges</title>
                <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
                <link href="https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/themes/prism.min.css" rel="stylesheet">
                <style>
                    .hero { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; }
                    .card { transition: transform 0.2s; }
                    .card:hover { transform: translateY(-5px); }
                    .endpoint { font-family: 'Courier New', monospace; }
                    .method-get { color: #28a745; }
                    .method-post { color: #007bff; }
                    .method-put { color: #ffc107; }
                    .method-patch { color: #17a2b8; }
                    .method-delete { color: #dc3545; }
                </style>
            </head>
            <body>
                <div class="hero py-5">
                    <div class="container text-center">
                        <h1 class="display-4 mb-3">🚀 API CRUD com Arrays</h1>
                        <p class="lead">OAT1 - Desenvolvimento de APIs - Professor Pedro Borges</p>
                        <p class="mb-4">Por: <strong>Gustavo</strong> | Curso: Sistemas de Informação</p>
                        <div class="row justify-content-center">
                            <div class="col-md-8">
                                <div class="d-flex gap-3 justify-content-center flex-wrap">
                                    <a href="#documentation" class="btn btn-light btn-lg">📚 Documentação</a>
                                    <a href="#postman" class="btn btn-outline-light btn-lg">📮 Postman</a>
                                    <a href="#endpoints" class="btn btn-outline-light btn-lg">🔗 Endpoints</a>
                                    <a href="https://github.com/Guztaver/oat-pedro-apis" class="btn btn-outline-light btn-lg" target="_blank">💻 GitHub</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="container my-5">
                    <!-- Informações do Projeto -->
                    <section id="info" class="mb-5">
                        <div class="row">
                            <div class="col-md-4 mb-4">
                                <div class="card h-100">
                                    <div class="card-body text-center">
                                        <h5 class="card-title">✅ Funcionalidades</h5>
                                        <ul class="list-unstyled">
                                            <li><strong>C</strong>reate - Criar itens</li>
                                            <li><strong>R</strong>ead - Listar/Buscar</li>
                                            <li><strong>U</strong>pdate - Atualizar</li>
                                            <li><strong>D</strong>elete - Deletar</li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4 mb-4">
                                <div class="card h-100">
                                    <div class="card-body text-center">
                                        <h5 class="card-title">🛠️ Tecnologias</h5>
                                        <ul class="list-unstyled">
                                            <li>Node.js + Express</li>
                                            <li>Arrays (Memória)</li>
                                            <li>Swagger/OpenAPI</li>
                                            <li>GitHub Pages</li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4 mb-4">
                                <div class="card h-100">
                                    <div class="card-body text-center">
                                        <h5 class="card-title">📊 Status</h5>
                                        <p class="text-success"><strong>✅ Projeto Completo</strong></p>
                                        <p>Todas as operações CRUD implementadas e testadas</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>

                    <!-- Como Usar -->
                    <section id="postman" class="mb-5">
                        <h2 class="text-center mb-4">📮 Importação Automática no Postman</h2>
                        <div class="row">
                            <div class="col-md-6 mb-4">
                                <div class="card">
                                    <div class="card-header bg-primary text-white">
                                        <h5 class="mb-0">🎯 Método 1: Swagger (Mais Fácil)</h5>
                                    </div>
                                    <div class="card-body">
                                        <ol>
                                            <li>Abra o Postman</li>
                                            <li>Import → Link</li>
                                            <li>Cole: <code>http://localhost:3000/api-docs</code></li>
                                            <li>✅ Todas as rotas importadas!</li>
                                        </ol>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6 mb-4">
                                <div class="card">
                                    <div class="card-header bg-success text-white">
                                        <h5 class="mb-0">📁 Método 2: Arquivo JSON</h5>
                                    </div>
                                    <div class="card-body">
                                        <ol>
                                            <li><a href="./postman-collection.json" download>Baixar Collection</a></li>
                                            <li><a href="./postman-environment.json" download>Baixar Environment</a></li>
                                            <li>Import → Upload Files</li>
                                            <li>✅ Collection completa!</li>
                                        </ol>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>

                    <!-- Endpoints -->
                    <section id="endpoints" class="mb-5">
                        <h2 class="text-center mb-4">🔗 Endpoints da API</h2>
                        <div class="table-responsive">
                            <table class="table table-striped">
                                <thead class="table-dark">
                                    <tr>
                                        <th>Método</th>
                                        <th>Endpoint</th>
                                        <th>Descrição</th>
                                        <th>CRUD</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td><span class="badge bg-info method-get">GET</span></td>
                                        <td class="endpoint">/</td>
                                        <td>Informações da API</td>
                                        <td>-</td>
                                    </tr>
                                    <tr>
                                        <td><span class="badge bg-primary method-post">POST</span></td>
                                        <td class="endpoint">/items</td>
                                        <td>Criar novo item</td>
                                        <td><strong>C</strong>reate</td>
                                    </tr>
                                    <tr>
                                        <td><span class="badge bg-success method-get">GET</span></td>
                                        <td class="endpoint">/items</td>
                                        <td>Listar todos os itens</td>
                                        <td><strong>R</strong>ead</td>
                                    </tr>
                                    <tr>
                                        <td><span class="badge bg-success method-get">GET</span></td>
                                        <td class="endpoint">/items/:id</td>
                                        <td>Buscar item por ID</td>
                                        <td><strong>R</strong>ead</td>
                                    </tr>
                                    <tr>
                                        <td><span class="badge bg-warning method-put">PUT</span></td>
                                        <td class="endpoint">/items/:id</td>
                                        <td>Atualizar item completo</td>
                                        <td><strong>U</strong>pdate</td>
                                    </tr>
                                    <tr>
                                        <td><span class="badge bg-info method-patch">PATCH</span></td>
                                        <td class="endpoint">/items/:id</td>
                                        <td>Atualizar item parcial</td>
                                        <td><strong>U</strong>pdate</td>
                                    </tr>
                                    <tr>
                                        <td><span class="badge bg-danger method-delete">DELETE</span></td>
                                        <td class="endpoint">/items/:id</td>
                                        <td>Deletar item</td>
                                        <td><strong>D</strong>elete</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </section>

                    <!-- Documentação -->
                    <section id="documentation" class="mb-5">
                        <h2 class="text-center mb-4">📚 Documentação</h2>
                        <div class="row">
                            <div class="col-md-6 mb-4">
                                <div class="card">
                                    <div class="card-header">
                                        <h5 class="mb-0">📖 Estrutura do Item</h5>
                                    </div>
                                    <div class="card-body">
                                        <pre><code class="language-json">{
              "id": 1,
              "name": "string (obrigatório)",
              "description": "string (obrigatório)", 
              "category": "string (opcional)",
              "price": "number (opcional)",
              "createdAt": "ISO Date",
              "updatedAt": "ISO Date"
            }</code></pre>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6 mb-4">
                                <div class="card">
                                    <div class="card-header">
                                        <h5 class="mb-0">🚀 Exemplo de Uso</h5>
                                    </div>
                                    <div class="card-body">
                                        <pre><code class="language-bash">curl -X POST http://localhost:3000/items \
              -H "Content-Type: application/json" \
              -d '{
                "name": "Notebook Dell",
                "description": "Notebook Dell Inspiron 15",
                "category": "Eletrônicos",
                "price": 2500
              }'</code></pre>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>

                    <!-- Links -->
                    <section class="text-center">
                        <h2 class="mb-4">🔗 Links Úteis</h2>
                        <div class="d-flex gap-3 justify-content-center flex-wrap">
                            <a href="https://github.com/Guztaver/oat-pedro-apis" class="btn btn-outline-primary" target="_blank">
                                💻 Código Fonte
                            </a>
                            <a href="./README.md" class="btn btn-outline-secondary" target="_blank">
                                📄 README
                            </a>
                            <a href="./postman-collection.json" class="btn btn-outline-success" download>
                                📮 Collection Postman
                            </a>
                            <a href="./example-data.js" class="btn btn-outline-info" target="_blank">
                                📊 Dados de Exemplo
                            </a>
                            <a href="./ENTREGA.md" class="btn btn-outline-warning" target="_blank">
                                📋 Informações de Entrega
                            </a>
                        </div>
                    </section>
                </div>

                <footer class="bg-dark text-white py-4 mt-5">
                    <div class="container text-center">
                        <p class="mb-2">
                            <strong>API CRUD com Arrays - OAT1</strong><br>
                            Disciplina: Desenvolvimento de APIs | Professor: Pedro Borges<br>
                            Aluno: Gustavo | Curso: Sistemas de Informação
                        </p>
                        <p class="mb-0">
                            <small>Projeto desenvolvido com Node.js, Express e hospedado no GitHub Pages</small>
                        </p>
                    </div>
                </footer>

                <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
                <script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/components/prism-core.min.js"></script>
                <script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/plugins/autoloader/prism-autoloader.min.js"></script>
            </body>
            </html>
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4